from sys import stdout

memory = [0] * 10
pointer = 0
buffer = []
pointer += 1
if pointer >= len(memory): memory.append(0)
pointer += 1
if pointer >= len(memory): memory.append(0)
pointer += 1
if pointer >= len(memory): memory.append(0)
pointer += 1
if pointer >= len(memory): memory.append(0)
memory[pointer] += 1
memory[pointer] += 1
pointer += 1
if pointer >= len(memory): memory.append(0)
memory[pointer] += 1
pointer += 1
if pointer >= len(memory): memory.append(0)
memory[pointer] += 1
memory[pointer] += 1
pointer += 1
if pointer >= len(memory): memory.append(0)
memory[pointer] += 1
pointer += 1
if pointer >= len(memory): memory.append(0)
pointer += 1
if pointer >= len(memory): memory.append(0)
memory[pointer] += 1
memory[pointer] += 1
pointer -= 1
if pointer < 0: pointer = 0
memory[pointer] += 1
while memory[pointer] != 0:
	while memory[pointer] != 0:
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		while memory[pointer] != 0:
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			while memory[pointer] != 0:
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			while memory[pointer] != 0:
				while memory[pointer] != 0:
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] += 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] -= 1
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
		memory[pointer] += 1
		pointer -= 1
		if pointer < 0: pointer = 0
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	memory[pointer] -= 1
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	memory[pointer] -= 1
	memory[pointer] -= 1
	while memory[pointer] != 0:
		memory[pointer] += 1
		while memory[pointer] != 0:
			memory[pointer] += 1
			memory[pointer] += 1
			memory[pointer] += 1
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			memory[pointer] -= 1
			memory[pointer] -= 1
		memory[pointer] += 1
		memory[pointer] += 1
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		memory[pointer] -= 1
		memory[pointer] -= 1
	memory[pointer] += 1
	while memory[pointer] != 0:
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
	pointer -= 1
	if pointer < 0: pointer = 0
	pointer -= 1
	if pointer < 0: pointer = 0
	pointer -= 1
	if pointer < 0: pointer = 0
	pointer -= 1
	if pointer < 0: pointer = 0
	while memory[pointer] != 0:
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		memory[pointer] += 1
		pointer -= 1
		if pointer < 0: pointer = 0
		memory[pointer] += 1
		pointer -= 1
		if pointer < 0: pointer = 0
	pointer -= 1
	if pointer < 0: pointer = 0
	pointer -= 1
	if pointer < 0: pointer = 0
	while memory[pointer] != 0:
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		while memory[pointer] != 0:
			while memory[pointer] != 0:
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] -= 1
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		while memory[pointer] != 0:
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		memory[pointer] -= 1
		while memory[pointer] != 0:
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			memory[pointer] += 1
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			memory[pointer] -= 1
		memory[pointer] += 1
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		while memory[pointer] != 0:
			memory[pointer] -= 1
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			while memory[pointer] != 0:
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
				memory[pointer] -= 1
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				memory[pointer] -= 1
				while memory[pointer] != 0:
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
				memory[pointer] += 1
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] += 1
				while memory[pointer] != 0:
					memory[pointer] -= 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] += 1
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			while memory[pointer] != 0:
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		while memory[pointer] != 0:
			memory[pointer] -= 1
			while memory[pointer] != 0:
				pointer -= 1
				if pointer < 0: pointer = 0
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] -= 1
		memory[pointer] += 1
		pointer -= 1
		if pointer < 0: pointer = 0
		while memory[pointer] != 0:
			memory[pointer] -= 1
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			while memory[pointer] != 0:
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
				memory[pointer] -= 1
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				memory[pointer] -= 1
				while memory[pointer] != 0:
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
				memory[pointer] += 1
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] += 1
				while memory[pointer] != 0:
					memory[pointer] -= 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] += 1
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			while memory[pointer] != 0:
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	memory[pointer] += 1
	while memory[pointer] != 0:
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
	memory[pointer] -= 1
	while memory[pointer] != 0:
		memory[pointer] += 1
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		memory[pointer] -= 1
		memory[pointer] -= 1
	memory[pointer] += 1
	memory[pointer] += 1
	while memory[pointer] != 0:
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
		pointer -= 1
		if pointer < 0: pointer = 0
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	pointer += 1
	if pointer >= len(memory): memory.append(0)
	memory[pointer] += 1
	while memory[pointer] != 0:
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		memory[pointer] -= 1
		while memory[pointer] != 0:
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			while memory[pointer] != 0:
				memory[pointer] -= 1
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
					memory[pointer] -= 1
				memory[pointer] -= 1
				pointer -= 1
				if pointer < 0: pointer = 0
				while memory[pointer] != 0:
					memory[pointer] -= 1
					while memory[pointer] != 0:
						memory[pointer] -= 1
						while memory[pointer] != 0:
							memory[pointer] += 1
							memory[pointer] += 1
							memory[pointer] += 1
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							memory[pointer] -= 1
						memory[pointer] += 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] -= 1
				memory[pointer] += 1
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] += 1
				while memory[pointer] != 0:
					memory[pointer] -= 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] += 1
				memory[pointer] += 1
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			while memory[pointer] != 0:
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				while memory[pointer] != 0:
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] -= 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
				memory[pointer] += 1
				pointer -= 1
				if pointer < 0: pointer = 0
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			memory[pointer] -= 1
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
		memory[pointer] += 1
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		while memory[pointer] != 0:
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			pointer += 1
			if pointer >= len(memory): memory.append(0)
		memory[pointer] -= 1
		while memory[pointer] != 0:
			memory[pointer] += 1
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			memory[pointer] -= 1
			memory[pointer] -= 1
		memory[pointer] += 1
		memory[pointer] += 1
		pointer -= 1
		if pointer < 0: pointer = 0
		while memory[pointer] != 0:
			while memory[pointer] != 0:
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			while memory[pointer] != 0:
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					while memory[pointer] != 0:
						pointer -= 1
						if pointer < 0: pointer = 0
						memory[pointer] -= 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] -= 1
					memory[pointer] += 1
					memory[pointer] += 1
					pointer -= 1
					if pointer < 0: pointer = 0
					while memory[pointer] != 0:
						while memory[pointer] != 0:
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							memory[pointer] -= 1
							pointer -= 1
							if pointer < 0: pointer = 0
							memory[pointer] -= 1
						memory[pointer] += 1
						memory[pointer] += 1
						while memory[pointer] != 0:
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
						memory[pointer] += 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] += 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] -= 1
					memory[pointer] += 1
					memory[pointer] += 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] -= 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					while memory[pointer] != 0:
						pointer -= 1
						if pointer < 0: pointer = 0
						memory[pointer] += 1
						while memory[pointer] != 0:
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
						pointer += 1
						if pointer >= len(memory): memory.append(0)
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
				memory[pointer] += 1
				pointer -= 1
				if pointer < 0: pointer = 0
				while memory[pointer] != 0:
					memory[pointer] -= 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					while memory[pointer] != 0:
						memory[pointer] -= 1
				memory[pointer] += 1
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		while memory[pointer] != 0:
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		while memory[pointer] != 0:
			memory[pointer] -= 1
			while memory[pointer] != 0:
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					memory[pointer] += 1
					memory[pointer] += 1
					memory[pointer] += 1
					memory[pointer] += 1
					while memory[pointer] != 0:
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] += 1
						memory[pointer] += 1
						memory[pointer] += 1
						memory[pointer] += 1
						memory[pointer] += 1
						memory[pointer] += 1
						memory[pointer] += 1
						memory[pointer] += 1
						pointer -= 1
						if pointer < 0: pointer = 0
						memory[pointer] -= 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
					stdout.write(chr(memory[pointer]))
					stdout.flush()
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
					while memory[pointer] != 0:
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						memory[pointer] -= 1
						memory[pointer] -= 1
						memory[pointer] -= 1
						memory[pointer] -= 1
						stdout.write(chr(memory[pointer]))
						stdout.flush()
						pointer -= 1
						if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					while memory[pointer] != 0:
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					while memory[pointer] != 0:
						memory[pointer] -= 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] += 1
					while memory[pointer] != 0:
						while memory[pointer] != 0:
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							pointer += 1
							if pointer >= len(memory): memory.append(0)
						memory[pointer] += 1
						while memory[pointer] != 0:
							memory[pointer] -= 1
							while memory[pointer] != 0:
								memory[pointer] -= 1
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								memory[pointer] += 1
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								memory[pointer] -= 1
								while memory[pointer] != 0:
									memory[pointer] -= 1
									while memory[pointer] != 0:
										memory[pointer] += 1
										memory[pointer] += 1
										memory[pointer] += 1
										pointer -= 1
										if pointer < 0: pointer = 0
										pointer -= 1
										if pointer < 0: pointer = 0
										pointer -= 1
										if pointer < 0: pointer = 0
										pointer -= 1
										if pointer < 0: pointer = 0
										while memory[pointer] != 0:
											memory[pointer] -= 1
									memory[pointer] += 1
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									memory[pointer] -= 1
								memory[pointer] += 1
								memory[pointer] += 1
								while memory[pointer] != 0:
									pointer -= 1
									if pointer < 0: pointer = 0
									pointer -= 1
									if pointer < 0: pointer = 0
									pointer -= 1
									if pointer < 0: pointer = 0
									pointer -= 1
									if pointer < 0: pointer = 0
							memory[pointer] += 1
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
							pointer -= 1
							if pointer < 0: pointer = 0
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
					memory[pointer] += 1
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] += 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				while memory[pointer] != 0:
					memory[pointer] -= 1
					while memory[pointer] != 0:
						memory[pointer] -= 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						while memory[pointer] != 0:
							memory[pointer] -= 1
							memory[pointer] -= 1
							while memory[pointer] != 0:
								memory[pointer] += 1
								memory[pointer] += 1
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								pointer += 1
								if pointer >= len(memory): memory.append(0)
								memory[pointer] -= 1
								memory[pointer] -= 1
							memory[pointer] -= 1
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							while memory[pointer] != 0:
								memory[pointer] -= 1
								while memory[pointer] != 0:
									memory[pointer] -= 1
									while memory[pointer] != 0:
										memory[pointer] += 1
										memory[pointer] += 1
										memory[pointer] += 1
										pointer -= 1
										if pointer < 0: pointer = 0
										pointer -= 1
										if pointer < 0: pointer = 0
										pointer -= 1
										if pointer < 0: pointer = 0
										pointer -= 1
										if pointer < 0: pointer = 0
										memory[pointer] -= 1
									memory[pointer] += 1
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									pointer += 1
									if pointer >= len(memory): memory.append(0)
									memory[pointer] -= 1
							memory[pointer] += 1
							memory[pointer] += 1
							pointer -= 1
							if pointer < 0: pointer = 0
							memory[pointer] += 1
							while memory[pointer] != 0:
								memory[pointer] -= 1
								pointer -= 1
								if pointer < 0: pointer = 0
								pointer -= 1
								if pointer < 0: pointer = 0
								pointer -= 1
								if pointer < 0: pointer = 0
								pointer -= 1
								if pointer < 0: pointer = 0
								memory[pointer] += 1
							memory[pointer] += 1
							memory[pointer] += 1
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							pointer += 1
							if pointer >= len(memory): memory.append(0)
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						while memory[pointer] != 0:
							pointer += 1
							if pointer >= len(memory): memory.append(0)
							while memory[pointer] != 0:
								pointer -= 1
								if pointer < 0: pointer = 0
								pointer -= 1
								if pointer < 0: pointer = 0
								pointer -= 1
								if pointer < 0: pointer = 0
								pointer -= 1
								if pointer < 0: pointer = 0
							memory[pointer] += 1
							pointer -= 1
							if pointer < 0: pointer = 0
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] -= 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
					pointer -= 1
					if pointer < 0: pointer = 0
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				while memory[pointer] != 0:
					memory[pointer] -= 1
					memory[pointer] -= 1
					while memory[pointer] != 0:
						memory[pointer] += 1
						memory[pointer] += 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] -= 1
						memory[pointer] -= 1
					memory[pointer] -= 1
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] -= 1
					memory[pointer] -= 1
					while memory[pointer] != 0:
						memory[pointer] += 1
						memory[pointer] += 1
						memory[pointer] += 1
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						pointer += 1
						if pointer >= len(memory): memory.append(0)
						memory[pointer] -= 1
						memory[pointer] -= 1
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] += 1
					while memory[pointer] != 0:
						memory[pointer] -= 1
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						pointer -= 1
						if pointer < 0: pointer = 0
						memory[pointer] += 1
					memory[pointer] += 1
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				while memory[pointer] != 0:
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			while memory[pointer] != 0:
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] += 1
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				memory[pointer] += 1
				memory[pointer] += 1
				pointer -= 1
				if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		while memory[pointer] != 0:
			memory[pointer] += 1
			pointer += 1
			if pointer >= len(memory): memory.append(0)
			while memory[pointer] != 0:
				memory[pointer] -= 1
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
					memory[pointer] -= 1
				memory[pointer] -= 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				memory[pointer] -= 1
				memory[pointer] -= 1
				while memory[pointer] != 0:
					memory[pointer] += 1
					memory[pointer] += 1
					memory[pointer] += 1
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					pointer += 1
					if pointer >= len(memory): memory.append(0)
					memory[pointer] -= 1
					memory[pointer] -= 1
				memory[pointer] += 1
				pointer -= 1
				if pointer < 0: pointer = 0
				memory[pointer] += 1
				while memory[pointer] != 0:
					memory[pointer] -= 1
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					pointer -= 1
					if pointer < 0: pointer = 0
					memory[pointer] += 1
				memory[pointer] += 1
				memory[pointer] += 1
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
				pointer += 1
				if pointer >= len(memory): memory.append(0)
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			pointer -= 1
			if pointer < 0: pointer = 0
			while memory[pointer] != 0:
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
				pointer -= 1
				if pointer < 0: pointer = 0
		pointer += 1
		if pointer >= len(memory): memory.append(0)
		pointer += 1
		if pointer >= len(memory): memory.append(0)
	pointer += 1
	if pointer >= len(memory): memory.append(0)
